### PR TITLE
Introducing the FPA bounties program

### PR DESCRIPTION
**Pull request by yorikvanhavre**

### CODE REVIEW

**Comment by Reqrefusion** [comment]
First of all, I leave the main reason why I was tagged here as a quote from the relevant part of the [FPA Admin agenda](https://docs.google.com/document/d/127iLZ-pdgbrU77ev2U5Zrogakt98RfugNp8mt0Lvj3s/edit?tab=t.0).

> DISCUSS: post facto Grants 
> From [Sunday Dev Meeting - agenda item 4](https://github.com/FreeCAD/FreeCAD-developer-meetings/blob/main/Agendas/agenda-2024-11-03.md)
> Example was a bug fixer who doesn’t want to create a proposal until most of the work is done.
> Grants cannot be requested after the work is completed. Grants are not given for every study conducted on a related problem. In order to receive a grant, a grant proposal must be submitted following standard grant procedures. Kadet also said at the meeting that grants should be considered for both difficult and boring work.(reqrefusion)
> The process might work like this: 
> A FPA member initiates a vote to prioritize granting for an issue based on community feedback. 
> The vote works the same way as grant proposals, except that the person making the proposal cannot vote. 
> If the vote is accepted, the issue is labeled as "prioritized granting" and a message is written stating that interested parties can submit a grant proposal. If it is not accepted, it is written that the issue is not a priority and is not included in this program, but a standard grant proposal will still be made. 
> The process that follows is the same as the "Fixed Goal" grant process. 
> In this context, grant proposals cannot be rejected, but the FPA may consider a higher or lower grant amount appropriate for the work done. The FPA declares the amount and the proposer can reject or accept it. If the FPA does not make a different proposal for the amount, the grant request is considered accepted.

My first problem, probably the biggest of my problems, is that we use the name "bounty". Frankly, I think the name bount should be avoided. Because bounties are standard for such things and contain traditional meanings. In this regard, it would be more accurate to treat it as a type of "Fixed Goal" grant rather than a bounty. The names I found for this are "issue prioritized for grant", "grantable issue", I will write it down if I think of it. This prevents a distinction between grant and bounty, and the existing grant technical committee can be continued without the need for an bounty committee. So there is no extra branching. Besides, we're not in the wild west, are we? These bounties always remind me of that. So, to put it technically, they have a pejorative meaning.

In my previous proposal, I suggested voting by the FPA, but in this proposal, this voting was excluded, and I think the FPA was excluded in general. In my opinion, the FPA vote should have been a must, especially if, like me, it is thought of as a sub-branch of the grant, the vote cannot be left out. I didn't make it clear that what's put to vote has to be suggested by the community, but it's fair to add it. FPA admins must bring an issue suggested by the community to the FPA vote. Here the relevant issue should be subjected to the normal voting process. Here, FPA admins should consider whether the community has a real demand for this issue or whether it is just an illusion, and vote based on whether the benefit is greater than the effort required. To make the process a little more difficult, the person who brings the proposal cannot vote. In fact, it is a bit similar to FPA-Designed grants here. The main purpose here, of course, is to gain legitimacy. Because ultimately this money will come out of the FPA and every member should have a say in the release of this money.

I also believe that existing grant procedures should be followed during this process. In other words, the person who wants to solve the "prioritized issue in the grant" must create a grant proposal before solving this problem. This can be done at any stage of the process, but if the relevant PR is accepted and the application cannot be made later. This is to continue the normal flow of life. Also, I think there is a really important issue here, which is the compensation to be given. Solving the issue properly can be a real time consuming thing. Maybe the person concerned will understand this later. I would like to remind you that the current grant system puts research at a very important place, which I think is one of its best aspects. In this way, the process is integrated into the grant system and the relevant person is prevented from being victimized. In addition, instead of a predetermined reward, he/she receives the compensation determined by the grant technical committee and himself/herself.

There is something beautiful here. A grant proposal that has received approval from the technical committee does not need to be approved again, as the FPA has already voted on this grant. However, the FPA may object to the compensation in the relevant offer. An objection from one FPA admin is sufficient for this. In response to the objection, the FPA, the Technical committee and the relevant person try to determine a compensation. This figure is then voted and accepted by the FPA. As can be seen here, the voting process has not even been voted on unless there is an expedited objection.

So, to summarize, the community around a problem communicates the importance of that problem. An FPA admin brings this issue to the FPA vote. The FPA makes a decision to ensure that this issue is truly prioritized. In line with the decision taken, a label is attached to the relevant problem. The relevant person who sees this tag submits a Fixed Goal grant offer to the FPA, stating that he can solve this problem or is currently solving it, along with a request for compensation and a deadline. The grant proposal is reviewed and approved by the technical committee. Any administrator within the FPA who is expressly dissatisfied with the relevant compensation may object to it. The technical committee, the FPA and the relevant person determine a new compensation or decide to resist. FPA votes on this as if it were a grant proposal.

It is useful to say that I base the processes here on the functioning of general institutions. Although the processes here aim to include certain facilitations, they are definitely aimed at ensuring legitimacy. FPA manages a relatively good amount of money and legitimacy must be maintained at every stage during this management. Another issue is that I do not believe that the current reward experiment is fully successful. I agree that these awards were effective in mobilizing the community working on it, but for each award it was effective to have someone involved with that problem. In short, it did not solve the problem, it only accelerated the solution of the problem. Of course, this is something that is sought after, but I am still not completely sure of this success.  In the last instance I believe that it would be better to add this wonderful system instead of making an exception to the current well-thought-out grant system.

Since I am writing while thinking for a while, there may be meaning shifts and meaninglessness, please write if there is anything that is not understood. Additionally, there may have been some problems due to the fact that I do not know the English equivalents of many legal words that I know in my own language.

**Comment by yorikvanhavre** [comment]
Well at the end it's still the FPA that decides to attribute or not the bounty... So I think we both agree here?

About the term "bounty", it woul be totally OK to use another one, no real preference here...

**Comment by Reqrefusion** [comment]
> Well at the end it's still the FPA that decides to attribute or not the bounty... So I think we both agree here?
> 
> About the term "bounty", it woul be totally OK to use another one, no real preference here...

Ultimately it is "Property is nine tenths of the law".

**Comment by Reqrefusion** [comment]
I would like to answer some questions from the meeting on my own behalf.
Unlike Yorik, I do not recommend bounties. In fact, I recommend that this name not be used.
In my suggestion, the person cannot claim the money after doing it. The relevant request is made in the form of a grant offer while the process is ongoing or before it begins.
My suggestion is not a bounty but a type of grant.
The only difference between my proposal and the normal grant is that the voting takes place in advance. Other processes work exactly like grants. The technical committee examines the proposal in the same way. There is no additional committee etc. FPA is deemed to have accepted by remaining silent. Voting can be done with objection, which turns it into a completely normal process. I wrote more details above.

**Comment by yorikvanhavre** [comment]
Closing by FPA decision

**Pull request closed without merging**
