### PR TITLE
FPA website style update and cleanup

### PR DESCRIPTION
**Pull request by marcuspollio**
Hi there !

Following Benjamin's (@benj5378) website modifications, here are a few further updates to its appearance.

Namely:

- CSS style cleanup, remove duplicates and unused classes
- less "flashy" colors (blue and pink) with shades of blue
- harmonize some texts, headings, sizes, margins, justification
- a few horizontal separators (rules) to make sections easier to read
- a few errors or link corrections here and there

<details>
  <summary><b>Click here for a few screenshots</b></summary>

FPAweb_1
---
FPAweb_2
---
FPAweb_3
---
FPAweb_4
---
FPAweb_5
---
FPAweb_6
---
FPAweb_7
---
FPAweb_8
</details>

### CODE REVIEW

**Comment by marcuspollio** [comment]
Ok, so this first update/cleanup is ready for review now.

I hope I didn't break too many things, fortunately not =P

Let me know what you think, thanks !

**Comment by yorikvanhavre** [comment]
Loved it! I like a lot that it's becoming a "variation", or a more "admin" version of the main FreeCAD website.

What would you think of making all tables use 100% of the width by default? Not sure about that... Also I'd like at some point to have a kind of easy "header" that gets the person back to the main FreeCAD website.

 In any case this is matter for another PR.

I'll let this one run a bit more in case anyone else wishes to comment, then I'll merge it

**Comment by marcuspollio** [comment]
Hi @yorikvanhavre !

> Loved it! 

Glad you do =D

> I like a lot that it's becoming a "variation", or a more "admin" version of the main FreeCAD website.

I'm not sure I got what you mean ?
Ideally, in the medium-term, I think it would be good to feel that all the websites around the FreeCAD ecosystem (main website, forum, Blog, FPA, etc.) belong to the same family, with a similar concept adapted to each particular case.
In this respect, Blender, Godot, Inkscape, Darktable to name but a few, are not too bad references...
Perhaps the approach of version 1.0 is the right opportunity for this ?
If the team of maintainers is up for it, we can set up a think tank among the UI/UX team and beyond.
 
> What would you think of making all tables use 100% of the width by default? Not sure about that...

Yeah, I'll give it a try soon

Thanks for having a look !

**Comment by yorikvanhavre** [comment]
Ok merged then. Thanks!!!

**Comment by yorikvanhavre** [comment]
I just meant I liked the colors ;)

**Pull request merged**
