### PR TITLE
New website

### PR DESCRIPTION
**Pull request by benj5378**
> That should also be changed at some point, I think the whole site should look good both rendered in pages and on github

This showed to become really difficult. Some issues being
- GitHub pages only supporting static MarkDown (no inclusion from other files)
- Firefox not supporting CSS :has pseudo class selector (for [16 years](https://bugzilla.mozilla.org/show_bug.cgi?id=418039), wtf), which were really important here
- Sass having a bug deleting a valid :has pseudo selector
- Liquid not supporting assignment of arrays and keys

So for a front page to look good, one had to either sacrifice GitHub pages or website layout... or do a few code duplications. I have really done my best to please both. These duplications are very minor. Please let me know of the layout, perhaps we could also ask the community for feedback - here is something to get going. I haven't made the layout responsive yet. Enjoy the screenshots, I hope you like it.

image

image

image

fpa new website

### CODE REVIEW

**Comment by benj5378** [comment]
image
image


Okay, it really sucks. It looks like GitHub doesn't even ignore liquid. Am I doing anything wrong here? Without these commands, it will be nearly impossible to do something with as simple things as button. I think the solution is to accept that GitHub won't look perfect.

**Comment by chennes** [comment]
IMO it's OK if it doesn't look great on GitHub. As far as I am concerned it only has to be legible enough to make it simple to make basic edits. Anything beyond that is unnecessary. @yorikvanhavre what do you think?

**Comment by yorikvanhavre** [comment]
LOVE IT!!!

Awesome work @benj5378 ! It looks so good that I'm okay to loose looking good on github :)

**Comment by yorikvanhavre** [comment]
It's merged! Awesome job @benj5378 !

**Comment by luzpaz** [comment]
Heads up @benj5378 

Screenshot_20230816_173343

* Bank Account text formatting isn't matching scheme
* Are we still using Bountysource ?

**Comment by WandererFan** [comment]
We still have a BountySource account, but it does not see much action.   

Getting money out of BountySource is a bit of an issue.  I'd be ok with not pushing donations towards that channel.

**Comment by benj5378** [comment]
image
@luzpaz hmm, for some reason your renders differently. What browser are you using? Another issue is the logo, only if the font is installed on device, it's rendered correctly.

**Comment by luzpaz** [comment]
Sorry about forgetting to mention that, FireFox 113.0 (64-bit)  

> Another issue is the logo, only if the font is installed on device, it's rendered correctly.

The browser won't automagically do this ?

**Comment by benj5378** [comment]
Yeah...I already guessed it was Firefox. For some reason, Firefox doesn't have full CSS selector support.

For the same reason, submenus of the website don't show in Firefox (though should still be accesible by an extra click). For 10 years, Firefox hasn't supported `:has` CSS selector...

**Pull request merged**
