### PR TITLE
Add Report 2

### PR DESCRIPTION
**Pull request by Francisco-Rosa**
Report 2, Creation of furniture and parametric components.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I see your comments and many videos, but I can't find the actual FCStd files you produced. Could you point me at them?

**Comment by Francisco-Rosa** [comment]
Yes of course.

Doors and windows:
https://github.com/Francisco-Rosa/Recently-created-FCStd-models/tree/main/Doors_windows
Doors_windows_R16.FCStd

Window images and videos
https://github.com/Francisco-Rosa/Recently-created-FCStd-models/tree/main/02-Windows

Ducts
FCStd:

https://github.com/Francisco-Rosa/FreeCAD-library/tree/master/HVAC/Ducts/Circular
Duct_curved_circular_reduction_complete_R01.FCStd
Duct_linear_circular_reduction_complete_R01.FCStd

https://github.com/Francisco-Rosa/FreeCAD-library/tree/master/HVAC/Ducts/Circular_oval
Duct_curved_oval_circular_reduction_complete_R00.FCStd
Duct_linear_circular_oval_complete_R00.FCStd

https://github.com/Francisco-Rosa/FreeCAD-library/tree/master/HVAC/Ducts/Flex
Duct_flex_complete_R00.FCStd

https://github.com/Francisco-Rosa/FreeCAD-library/tree/master/HVAC/Ducts/Oval
Duct_curved_oval_reduction_complete_R00.FCStd
Duct_linear_oval_complete_R00.FCStd

https://github.com/Francisco-Rosa/FreeCAD-library/tree/master/HVAC/Ducts/Rectangular
Duct_curved_rectangular_reduction_complete_R01.FCStd
Duct_linear_rectangular_reduction_complete_R01.FCStd

https://github.com/Francisco-Rosa/FreeCAD-library/tree/master/HVAC/Ducts/Rectangular_circular
Duct_curved_rectangular_circular_complete_R01.FCStd
Duct_linear_rectangular_circular_reduction_complete_R01.FCStd

https://github.com/Francisco-Rosa/FreeCAD-library/tree/master/HVAC/Ducts/Rectangular_oval
Duct_curved_rectangular_oval_complete_R00.FCStd
Duct_linear_rectangular_oval_complete_R00.FCStd

Videos:
https://github.com/Francisco-Rosa/FreeCAD-library/tree/master/HVAC/Ducts/Videos
Video_01_Ducts_rectangular_assembly_part_01.mp4
Video_02_Ducts_rectangular_assembly_part_02.mp4
Video_03_Ducts_rectangular_assembly_part_03.mp4

**Comment by Francisco-Rosa** [comment]
Did you take a look at the files?

I just updated the ducts files. Later on, I will delete the old files and leave only the newer ones.

**Comment by yorikvanhavre** [comment]
Thanks for the links! I'm away from my computer until tuesday, I'll have a look then. But it looks good!

**Comment by yorikvanhavre** [comment]
Okay I had a good look at all the files, they are very well detailed and the parametric system with all driving properties in one object is pretty cool. I have some concerns though, that some are overly complex (the window, mainly) and almost unusable by other users. I myself had to do some work to find out what was where... It's not clear at all what you need to do or copy to get a clean object that you can insert into your project, which is, after all, the goal of an objects library.

What about, next to those "master" objects, issuing a series of already "tailored" objects, that would be easily pastable/insertable into an existing model without having to deal with complex chains of objects? Not sure what form that should have, a series of step files might be good in some cases, but not as good in others (doors or windows, for ex, should still keep some basic properties such as making holes or be able to open).

**Pull request merged**
