### PR TITLE
New logo Guidelines and images update

### PR DESCRIPTION
**Pull request by sytabaresa**
New logo updates in `images` folder with:
- PDF and SVG version of guidelines, in `guidelines` folder
- PNG and SVG version of logos, short, long and mono version in `logos` folder, with:
  - Square logos (no padding) in `square`  subfolder
  - Social logos (small padding) in `social` subfolder
  - Maskable logos (big padding) in `maskable` subfolder
  - Mobile logos in `mobile` subfolder
  
 each PNG/SVG has the best pixel fit for every size

### CODE REVIEW

**Comment by maxwxyz** [comment]
images/FPALogo.svg would need a new version, otherwise there is no header image on fpa.freecad.org

**Comment by maxwxyz** [comment]
@chennes FYI.
Please also change it where the new logo was already uploaded to (GitHub, LinkedIn, forum favicon,...) as there were subtle changes to the gear and colors. The one in the `social` folder should be fine for GitHub and other accounts, the current one is e.g. cut off as it's displayed in a circle frame on mobile.
Who should be pinged to update the social profiles (twitter, mastodon, facebook, reddit, matrix...) they currently don't even use the same logo.

@prokoudine maybe you could update the blog post with one of the images here.

**Comment by prokoudine** [comment]
> @prokoudine maybe you could update the blog post with one of the images here.

Done!

**Comment by MisterMakerNL** [comment]
The off-block mentioned in the guide isn't the same as the off-black not used.

**Comment by sytabaresa** [comment]
> The off-black mentioned in the guide isn't the same as the off-black used.

O wow, My error, changing as soon as posible

**Comment by sytabaresa** [comment]
Fixed colors and remove needless SVGs for square, social, maskable, etc.

**Comment by maxwxyz** [comment]
great, thank you!

**Comment by maxwxyz** [comment]
@chennes is something holding this back or when will it be merged?

**Comment by chennes** [comment]
> @chennes is something holding this back or when will it be merged?

When I notice it exists 😁

**Comment by chennes** [comment]
Oops, this breaks the FPA site, you removed the FPA logo. Could you please make a PR that restores it?

**Pull request merged**
